#!/bin/bash
#SBATCH -n 1 # Number of processos
#SBATCH -c 10 # Number of cores
#SBATCH --mem 60G # 60GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m5
# commanda terminal --> sbatch --gres gpu:1 -n 10 job_task_e
python task_e.py --margin 1 --learning_rate 1e-4 --weighted True
python task_e.py --margin 1 --learning_rate 1e-5 --weighted True

